/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzerRouteImport } from './routes/analyzer'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as BiosRouteImport } from './routes/bios'
import { Route as CleanerRouteImport } from './routes/cleaner'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as MigrateRouteImport } from './routes/migrate'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as SetupRouteImport } from './routes/setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerRoute = AnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const BiosRoute = BiosRouteImport.update({
  id: '/bios',
  path: '/bios',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanerRoute = CleanerRouteImport.update({
  id: '/cleaner',
  path: '/cleaner',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrateRoute = MigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/backup': typeof BackupRoute
  '/bios': typeof BiosRoute
  '/cleaner': typeof CleanerRoute
  '/duplicates': typeof DuplicatesRoute
  '/library': typeof LibraryRoute
  '/migrate': typeof MigrateRoute
  '/organizer': typeof OrganizerRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/backup': typeof BackupRoute
  '/bios': typeof BiosRoute
  '/cleaner': typeof CleanerRoute
  '/duplicates': typeof DuplicatesRoute
  '/library': typeof LibraryRoute
  '/migrate': typeof MigrateRoute
  '/organizer': typeof OrganizerRoute
  '/setup': typeof SetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/backup': typeof BackupRoute
  '/bios': typeof BiosRoute
  '/cleaner': typeof CleanerRoute
  '/duplicates': typeof DuplicatesRoute
  '/library': typeof LibraryRoute
  '/migrate': typeof MigrateRoute
  '/organizer': typeof OrganizerRoute
  '/setup': typeof SetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyzer'
    | '/backup'
    | '/bios'
    | '/cleaner'
    | '/duplicates'
    | '/library'
    | '/migrate'
    | '/organizer'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyzer'
    | '/backup'
    | '/bios'
    | '/cleaner'
    | '/duplicates'
    | '/library'
    | '/migrate'
    | '/organizer'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/analyzer'
    | '/backup'
    | '/bios'
    | '/cleaner'
    | '/duplicates'
    | '/library'
    | '/migrate'
    | '/organizer'
    | '/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzerRoute: typeof AnalyzerRoute
  BackupRoute: typeof BackupRoute
  BiosRoute: typeof BiosRoute
  CleanerRoute: typeof CleanerRoute
  DuplicatesRoute: typeof DuplicatesRoute
  LibraryRoute: typeof LibraryRoute
  MigrateRoute: typeof MigrateRoute
  OrganizerRoute: typeof OrganizerRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer': {
      id: '/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bios': {
      id: '/bios'
      path: '/bios'
      fullPath: '/bios'
      preLoaderRoute: typeof BiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaner': {
      id: '/cleaner'
      path: '/cleaner'
      fullPath: '/cleaner'
      preLoaderRoute: typeof CleanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrate': {
      id: '/migrate'
      path: '/migrate'
      fullPath: '/migrate'
      preLoaderRoute: typeof MigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzerRoute: AnalyzerRoute,
  BackupRoute: BackupRoute,
  BiosRoute: BiosRoute,
  CleanerRoute: CleanerRoute,
  DuplicatesRoute: DuplicatesRoute,
  LibraryRoute: LibraryRoute,
  MigrateRoute: MigrateRoute,
  OrganizerRoute: OrganizerRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
